__title__ = "python-ipware"
__author__ = "Val Neekman"
__author_email__ = "info@neekware.com"
__description__ = "A Python package to retrieve user's IP address"
__url__ = "https://github.com/un33k/python-ipware"
__license__ = "MIT"
__copyright__ = "Copyright 2023 Val Neekman @ Neekware Inc."
__version__ = "0.9.0"
